name: sistema_escolar
description: Sistema de Gestion Escolar EMCC
publish_to: 'none'
version: 4.10.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  mobile_scanner: ^3.5.7
  qr_flutter: ^4.1.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_bluetooth_serial: ^0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/data/emcc_sistema.db
